### ISSUE TITLE
Feedback:

### ISSUE THREAD

**Issue by FlorianHeigl** [crystone/docker-monitoring#1]
Very nice!

I've gone through 4 or 5 check plugins today, this one is the best-working one! 
- has no dependencies that are superfluous to what it needs to check.
- sticks to a language that would be available where docker is available
- checks a sensible mix of things
- is not broken on a modern version of docker

I'm not even a fan of Docker, but clearly want it to work the best way possible, and make sure people will get alerts if anything isn't running 100% smooth.

A big **Thank You!** for publishing this plugin.

**Comment by tobias-urdin** [comment]
Thanks for your feedback :thumbsup:
